[package]
name = "kvs"
version = "0.1.0"
authors = ["Nicolas Thery <nicolas.thery@gmail.com>"]
edition = "2018"
description = "A key-value store"

[dependencies]

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
